networks:
  backend:
    driver: bridge


version: '3'
services:

  consul:
    image: "consul:1.15.4"
    hostname: "im-consul"
    command: "agent -dev -client 0.0.0.0 -ui"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    networks:
      - backend